bordercolor=0x{fg.strip}ff
focuscolor=0x{accent.strip}ff

rootcolor=0x{bg.strip}ff
maximizescreencolor=0x{accent.strip}ff
urgentcolor=0x{red.strip}ff
scratchpadcolor=0x{yellow.strip}ff
globalcolor=0x{color5.strip}ff
overlaycolor=0x{surface.strip}cc