[General]
Font="CaskaydiaCove Nerd Font Mono"
FontSize=10

PasswordShowLastLetter=1000

# [Colors]
hower     = "#8B8176"
text      = "#d4be98"
surface2  = "#A59783"
surface1  = "#343333"
surface0  = "#2A2A2B"
overlay   = "#3F403C"
border    = "#48443F"
base      = "#292929"
Primary   = "#d4be98"
onPrimary = "#232634"

## [Locale Settings]
Locale=""
HourFormat="HH:mm"
DateFormat = "ddd dd"