theme = "gruvbox"
enable_transparency=false
enable_backdrop = false

max_clipboard_history = 1000

[[search_providers]]
name = "YouTube"
trigger = "!yt"
url = "https://youtube.com/search?q={query}"
icon = "youtube-logo"
