theme = "gruvbox"
# launcher_size = [600, 400]
enable_transparency=false
window_size = [2256, 1404] # Cover all monitors, this is also the highest possible value

max_clipboard_history = 1000

[[search_providers]]
name = "YouTube"
trigger = "!yt"
url = "https://youtube.com/search?q={query}"
icon = "youtube-logo"
