#####################
# AUTOSTART
#####################
exec-once=kwalletd6
exec-once=zlaunch
exec-once=vibepanel
exec-once=awww-daemon
exec-once=kdeconnectd
exec-once=dex -a # Run all autostart apps in ~/.config/autostart and /etc/xdg/autostart/
exec-once=systemctl --user start hyprpolkitagent
exec-once=veilad

exec-once=wlsunset -T 4001