#####################
# AUTOSTART
#####################
# exec-once=kwalletd6
exec-once=zlaunch
exec-once=vibepanel
exec-once=awww-daemon
# exec-once=kdeconnectd
exec-once=dex -a # Run all autostart apps in ~/.config/autostart and /etc/xdg/autostart/
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=veilad

exec-once=wlsunset -T 4001

exec-once=xwayland-satellite :2 # Fix blurry x11 windows when using scaling
