#####################
# MONITORS
#####################
monitorrule=name:^eDP-1$,width:2256,height:1504,refresh:60,x:0,y:0,scale:1.4
monitorrule=name:^DP-4$,width:1920,height:1080,refresh:144,x:0,y:-1080,scale:1


syncobj_enable=1 # Fixes some flickering and bugs on nvidia
