#####################
# MONITORS
#####################
monitorrule=name:^eDP-1$,width:2256,height:1504,refresh:60,x:0,y:0,scale:1.4

xwayland_ignore_scale=1
exec-once=echo "Xft.dpi: 135" | xrdb -merge