#####################
# STYLING
#####################
tag_animation_direction=0

bordercolor = 0xd4be98ff
focuscolor = 0x7daea3ff

rootcolor = 0x1d1a16ff
maximizescreencolor = 0x7daea3ff
urgentcolor = 0xea6962ff
scratchpadcolor = 0xfe8019ff
globalcolor = 0xb16286ff
overlaycolor = 0x3c3836cc
