#####################
# STYLING
#####################

# Colors
source=~/.cache/iris/mango.conf
# TODO:  wallpapcker picker which triggers both "iris $wallpaper" and "mmsg dispatch reload_config"

# Cursor
env=XCURSOR_SIZE,24
cursor_size=24
env=XCURSOR_THEME,Bibata-Modern-Ice
cursor_theme=Bibata-Modern-Ice


# Animations
tag_animation_direction=0

# Window effects
blur=0
blur_layer=0
blur_optimized=1
blur_params_radius=8
blur_params_num_passes=2
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.2


border_radius=0

# Space between apps
gappih=10
gappiv=10

# Space between outer border
gappoh=10
gappov=10

# Border size
borderpx=5