#####################
# STYLING
#####################

# Colors
source=~/.cache/iris/mango.conf
# TODO: mmsg dispatch reload_config to reload mango colors
# TODO: foot terminal proper color template (https://github.com/Harman1307/iris#custom-templates)

# Cursor
env=XCURSOR_SIZE,24
cursor_size=24
env=XCURSOR_THEME,Bibata-Modern-Ice
cursor_theme=Bibata-Modern-Ice


# Animations
tag_animation_direction=0

# Window effects
blur=1
blur_layer=0
blur_optimized=1
blur_params_radius=8
blur_params_num_passes=2
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.2

shadows=1
layer_shadows=1
shadow_only_floating=1
shadows_size=12
shadows_blur=25
shadows_position_x=0
shadows_position_y=0
shadowscolor=0x000000ff

border_radius=10

focused_opacity=0.90
unfocused_opacity=0.75